# Generated by Django 2.2.11 on 2022-07-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.TextField()),
                ('poster', models.TextField(blank=True, null=True)),
                ('imdbid', models.TextField()),
                ('year', models.TextField()),
            ],
        ),
    ]
